import { z } from "zod";

export const ACCOUNT_TYPES = [
  "asset",
  "liability",
  "equity",
  "income",
  "expense",
] as const;

export const ACCOUNT_SUB_TYPES = [
  // Assets
  "current_asset",
  "fixed_asset",
  "inventory",
  "bank",
  "cash",
  "accounts_receivable",
  "prepaid_expenses",
  "other_current_asset",
  // Liabilities
  "current_liability",
  "long_term_liability",
  "accounts_payable",
  "credit_card",
  "tax_payable",
  "accrued_expenses",
  "other_current_liability",
  // Equity
  "equity",
  "retained_earnings",
  "share_capital",
  // Income
  "operating_income",
  "other_income",
  "sales_revenue",
  "service_revenue",
  // Expenses
  "operating_expense",
  "cost_of_goods_sold",
  "other_expense",
  "salary_expense",
  "rent_expense",
  "utility_expense",
] as const;

export const accountSchema = z.object({
  id: z.string().optional(),
  code: z.string().min(1, "Account code is required"), // e.g., 1000, 1010
  name: z.string().min(1, "Account name is required"),
  type: z.enum(ACCOUNT_TYPES),
  subType: z.enum(ACCOUNT_SUB_TYPES),
  parentId: z.string().optional(),
  description: z.string().optional(),
  isActive: z.boolean().default(true),
  isSystemAccount: z.boolean().default(false), // System accounts cannot be deleted (e.g., Accounts Receivable)
  currency: z.string().default("USD"),
  currentBalance: z.number().default(0), // Cached balance, actual balance is sum of journal entries
  reconcile: z.boolean().default(false), // Whether this account can be reconciled (bank accounts)
  allowManualEntries: z.boolean().default(true), // Whether manual journal entries are allowed
  deprecated: z.boolean().default(false), // Mark deprecated accounts
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});

export type AccountType = typeof ACCOUNT_TYPES[number];
export type AccountSubType = typeof ACCOUNT_SUB_TYPES[number];
export type Account = z.infer<typeof accountSchema>;
export type CreateAccountDTO = Omit<Account, "id" | "createdAt" | "updatedAt">;
export type UpdateAccountDTO = Partial<CreateAccountDTO>;

/**
 * Default Chart of Accounts template
 * Based on standard accounting practices
 */
export const DEFAULT_CHART_OF_ACCOUNTS: Omit<CreateAccountDTO, "isActive">[] = [
  // ASSETS (1000-1999)
  {
    code: "1000",
    name: "Cash",
    type: "asset",
    subType: "cash",
    isSystemAccount: true,
    reconcile: true,
    currency: "USD",
    currentBalance: 0,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "1100",
    name: "Bank",
    type: "asset",
    subType: "bank",
    isSystemAccount: true,
    reconcile: true,
    currency: "USD",
    currentBalance: 0,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "1200",
    name: "Accounts Receivable",
    type: "asset",
    subType: "accounts_receivable",
    isSystemAccount: true,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "1300",
    name: "Inventory",
    type: "asset",
    subType: "inventory",
    isSystemAccount: true,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "1400",
    name: "Prepaid Expenses",
    type: "asset",
    subType: "prepaid_expenses",
    isSystemAccount: false,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "1500",
    name: "Fixed Assets",
    type: "asset",
    subType: "fixed_asset",
    isSystemAccount: false,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "1600",
    name: "Accumulated Depreciation",
    type: "asset",
    subType: "fixed_asset",
    isSystemAccount: false,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  
  // LIABILITIES (2000-2999)
  {
    code: "2000",
    name: "Accounts Payable",
    type: "liability",
    subType: "accounts_payable",
    isSystemAccount: true,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "2100",
    name: "Tax Payable",
    type: "liability",
    subType: "tax_payable",
    isSystemAccount: true,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "2200",
    name: "Credit Card Payable",
    type: "liability",
    subType: "credit_card",
    isSystemAccount: false,
    reconcile: true,
    currency: "USD",
    currentBalance: 0,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "2300",
    name: "Accrued Expenses",
    type: "liability",
    subType: "accrued_expenses",
    isSystemAccount: false,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "2400",
    name: "Long Term Liabilities",
    type: "liability",
    subType: "long_term_liability",
    isSystemAccount: false,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  
  // EQUITY (3000-3999)
  {
    code: "3000",
    name: "Share Capital",
    type: "equity",
    subType: "share_capital",
    isSystemAccount: true,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "3100",
    name: "Retained Earnings",
    type: "equity",
    subType: "retained_earnings",
    isSystemAccount: true,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  
  // INCOME (4000-4999)
  {
    code: "4000",
    name: "Sales Revenue",
    type: "income",
    subType: "sales_revenue",
    isSystemAccount: true,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "4100",
    name: "Service Revenue",
    type: "income",
    subType: "service_revenue",
    isSystemAccount: true,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "4200",
    name: "Other Income",
    type: "income",
    subType: "other_income",
    isSystemAccount: false,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  
  // EXPENSES (5000-5999)
  {
    code: "5000",
    name: "Cost of Goods Sold",
    type: "expense",
    subType: "cost_of_goods_sold",
    isSystemAccount: true,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "5100",
    name: "Salary Expense",
    type: "expense",
    subType: "salary_expense",
    isSystemAccount: false,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "5200",
    name: "Rent Expense",
    type: "expense",
    subType: "rent_expense",
    isSystemAccount: false,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "5300",
    name: "Utility Expense",
    type: "expense",
    subType: "utility_expense",
    isSystemAccount: false,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "5400",
    name: "Operating Expenses",
    type: "expense",
    subType: "operating_expense",
    isSystemAccount: false,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
  {
    code: "5500",
    name: "Other Expenses",
    type: "expense",
    subType: "other_expense",
    isSystemAccount: false,
    currency: "USD",
    currentBalance: 0,
    reconcile: false,
    allowManualEntries: true,
    deprecated: false,
  },
];
